### ISSUE TITLE
[Enhancement] Support Excel Sheet

### ISSUE THREAD

**Issue by zerorail** [josereia/libre_doc_converter#1]
hello 

I really like you work, you have done a great job by bringing this library to flutter

But, can you also support excel sheets convert?

**Comment by josereia** [comment]
Hello!

Glad you liked the library. In fact it already supports excel spreadsheets(.xls and .xlsx) I just forgot to mention it and add an example in the documentation.

I've just updated the library and documentation on pub.dev. You can check it out and use it as you wish.
